<a href="https://colab.research.google.com/github/Felixxx228/MachineLearning/blob/main/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np

2) Создать нулевой вектор размера 10

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
np.full((7),7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
arr = np.arange(102)
print(arr[10:102:2])

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
arr = np.random.randint(0,20, 10)
print(arr[::-1])

[ 2  4  4 11  5 11 16  1  1 11]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
arr = np.arange(9)
arr = arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
arr = np.eye(4, k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
arr = np.full((4,4) ,7)

print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
import numpy as np

arr = np.zeros((5,5))
arr += np.arange(5)

print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [9]:
arr = np.random.randint(0, 100, size=(10, 10))
print(arr)
average = np.mean(arr, axis = 1)
center = arr - average[:, np.newaxis]
print(center)

[[45  9 15 86 95 97 10 51 68 55]
 [99 45 21 75 14 11 31 32 69 80]
 [75  5 44 43 84 24 87  8 27 83]
 [85 98 14 16 58  5 15  4 75 30]
 [23 52 17 28 16 81 61 53 37 80]
 [93 73  3 70 47 24 44 17 54 17]
 [26 21 47 86 97  4  8 77 41  0]
 [78  2 12 64 44 57 33 52 14 75]
 [56 82 53 42 26 82 62 29  3 24]
 [85 44 68  9 57 71 35 89 83 77]]
[[ -8.1 -44.1 -38.1  32.9  41.9  43.9 -43.1  -2.1  14.9   1.9]
 [ 51.3  -2.7 -26.7  27.3 -33.7 -36.7 -16.7 -15.7  21.3  32.3]
 [ 27.  -43.   -4.   -5.   36.  -24.   39.  -40.  -21.   35. ]
 [ 45.   58.  -26.  -24.   18.  -35.  -25.  -36.   35.  -10. ]
 [-21.8   7.2 -27.8 -16.8 -28.8  36.2  16.2   8.2  -7.8  35.2]
 [ 48.8  28.8 -41.2  25.8   2.8 -20.2  -0.2 -27.2   9.8 -27.2]
 [-14.7 -19.7   6.3  45.3  56.3 -36.7 -32.7  36.3   0.3 -40.7]
 [ 34.9 -41.1 -31.1  20.9   0.9  13.9 -10.1   8.9 -29.1  31.9]
 [ 10.1  36.1   7.1  -3.9 -19.9  36.1  16.1 -16.9 -42.9 -21.9]
 [ 23.2 -17.8   6.2 -52.8  -4.8   9.2 -26.8  27.2  21.2  15.2]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [11]:
arr = np.random.randint(0, 100, size = (10,10))
print(arr)

median = np.median(arr, axis = 0)
every = arr - median[:, np.newaxis]
print(every)

[[29 43 24  9  7 10 87 79 35 57]
 [36 71 47 55 65 88 27 92  4 86]
 [26 73 30 15  0 52 37 52 69 26]
 [46 48 48 58 24 51  5  7 24 23]
 [29 56 43 19 38 50 15 72 12 13]
 [45 20 43  1 18 36 10  4 44  6]
 [45 83 96 27 70 11 87 42  7 29]
 [ 1 52 34 95 23 93 47 95 60 78]
 [ 5 82 62  2 68 22 61  9 34 94]
 [ 9 71 34 73 18 58 18 62 16 81]]
[[  0.   14.   -5.  -20.  -22.  -19.   58.   50.    6.   28. ]
 [-27.5   7.5 -16.5  -8.5   1.5  24.5 -36.5  28.5 -59.5  22.5]
 [-17.   30.  -13.  -28.  -43.    9.   -6.    9.   26.  -17. ]
 [ 23.   25.   25.   35.    1.   28.  -18.  -16.    1.    0. ]
 [  5.5  32.5  19.5  -4.5  14.5  26.5  -8.5  48.5 -11.5 -10.5]
 [ -5.5 -30.5  -7.5 -49.5 -32.5 -14.5 -40.5 -46.5  -6.5 -44.5]
 [ 13.   51.   64.   -5.   38.  -21.   55.   10.  -25.   -3. ]
 [-56.   -5.  -23.   38.  -34.   36.  -10.   38.    3.   21. ]
 [-24.   53.   33.  -27.   39.   -7.   32.  -20.    5.   65. ]
 [-34.   28.   -9.   30.  -25.   15.  -25.   19.  -27.   38. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [12]:
matrix = np.random.randint(0, 100, size = (5, 5))
print(matrix)

max_value = np.max(matrix, axis = 1)
min_value = np.min(matrix, axis = 1)

with_max = np.column_stack((matrix, max_value))
final = np.column_stack((with_max, min_value))
print(final)

[[61 13 61 63 17]
 [60 20  4 81 16]
 [96 32 86 57 57]
 [57 10 10 44 28]
 [95 45 51 39 58]]
[[61 13 61 63 17 63 13]
 [60 20  4 81 16 81  4]
 [96 32 86 57 57 96 32]
 [57 10 10 44 28 57 10]
 [95 45 51 39 58 95 39]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [13]:
vector = np.arange(1, 51)

chet = vector[vector % 2 != 0]
nechet = vector[vector % 2 == 0]

chet_matrix = np.array([chet])
nechet_matrix = np.array([nechet])

print(chet_matrix)
print(nechet_matrix)

perem_matrix = chet_matrix * nechet_matrix
print(perem_matrix)

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
  49]]
[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]
[[   2   12   30   56   90  132  182  240  306  380  462  552  650  756
   870  992 1122 1260 1406 1560 1722 1892 2070 2256 2450]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [14]:
matrix = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i + j) % 2 == 0:
        matrix[i, j] = 1
    else:
      matrix[i, j] = 0

print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
